# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BusPosition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42usPosition.proto\"\xb8\x01\n\x0b\x42usPosition\x12\x1a\n\x12request_time_local\x18\x01 \x01(\t\x12\x16\n\x0eingestion_date\x18\x02 \x01(\x05\x12\x19\n\x11position_datetime\x18\x03 \x01(\t\x12\x0c\n\x04line\x18\x04 \x01(\t\x12\x0f\n\x07\x62rigade\x18\x05 \x01(\t\x12\x16\n\x0evehicle_number\x18\x06 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\x01\x12\x11\n\tlongitude\x18\x08 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BusPosition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUSPOSITION']._serialized_start=22
  _globals['_BUSPOSITION']._serialized_end=206
# @@protoc_insertion_point(module_scope)
